"""Initial migration3.

Revision ID: 7525274513b9
Revises: 074b8f3d5ab6
Create Date: 2024-10-12 15:07:38.233448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7525274513b9'
down_revision = '074b8f3d5ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_created_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_created_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
